name: CI - Build & Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting CI job..."

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker images
        run: |
          docker build -t tp-docker-cicd-backend ./backend
          docker build -t tp-docker-cicd-frontend ./frontend
          docker build -t tp-docker-cicd-database ./database

      - name: Start services
        run: docker-compose up -d

      - name: Basic API test
        run: curl -f http://localhost:3000/api

      - name: Stop containers
        run: docker-compose down

      - name: Complete job
        run: echo "Pipeline finished!"
